name: Update Blog Manifest

on:
  push:
    paths:
      - 'posts/*.md'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Generate posts.json
        run: node generate-posts-json.mjs

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          git add posts/posts.json
          git diff --cached --quiet || git commit -m "🤖 Auto-update posts.json"
          git push

